// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APBD_KOLOS2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240621113550_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APBD_KOLOS2.Models.Object", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<int>("Object_Type_ID")
                        .HasColumnType("int");

                    b.Property<int>("Warehouse_ID")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(4, 2)");

                    b.HasKey("ID");

                    b.HasIndex("Object_Type_ID");

                    b.HasIndex("Warehouse_ID");

                    b.ToTable("Object");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Height = 2.34m,
                            Object_Type_ID = 1,
                            Warehouse_ID = 1,
                            Width = 1.23m
                        },
                        new
                        {
                            ID = 2,
                            Height = 3.45m,
                            Object_Type_ID = 2,
                            Warehouse_ID = 2,
                            Width = 2.34m
                        });
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object_Owner", b =>
                {
                    b.Property<int>("Object_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("Owner_ID")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("Object_ID", "Owner_ID");

                    b.HasIndex("Owner_ID");

                    b.ToTable("Object_Owner");

                    b.HasData(
                        new
                        {
                            Object_ID = 1,
                            Owner_ID = 1
                        },
                        new
                        {
                            Object_ID = 2,
                            Owner_ID = 2
                        });
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object_Type", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Object_Type");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Type 1"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Type 2"
                        });
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("ID");

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123456789"
                        },
                        new
                        {
                            ID = 2,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987654321"
                        });
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Warehouse");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Warehouse A"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Warehouse B"
                        });
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object", b =>
                {
                    b.HasOne("APBD_KOLOS2.Models.Object_Type", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("Object_Type_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_KOLOS2.Models.Warehouse", "Warehouse")
                        .WithMany("Objects")
                        .HasForeignKey("Warehouse_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object_Owner", b =>
                {
                    b.HasOne("APBD_KOLOS2.Models.Object", "Object")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("Object_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_KOLOS2.Models.Owner", "Owner")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("Owner_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Object_Type", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Owner", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("APBD_KOLOS2.Models.Warehouse", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
